version: '3.8'

# FIX THIS FILE TOO
services:
  nextjs-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/app
    container_name: nextjs-docker
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']
