services:

  nextjs-docker:
    build: ./frontend
    container_name: nextjs-docker
    ports:
      - '3000:3000'
    command: ['bun', 'run', 'dev']

  node-api:
    build: ./backend/node
    container_name: node-api
    ports:
      - '3050:3050'
    networks:
      - backend

  python-api:
    build: ./backend/python
    container_name: python-api
    ports:
      - '3030:3030'
    networks:
      - backend
    
  
  networks:
    backend:
      driver: bridge