services:
  nextjs-docker:
    build: ./frontend
    container_name: nextjs-docker
    ports:
      - '3000:3000'
    command: ['bun', 'run', 'dev']
  # golang-backend:
  #   build: ./backend
  #   container_name: golang-backend
  #   ports:
  #     - '3030:3030'
