services:
  nextjs-docker:
    build: ./frontend
    container_name: nextjs-docker
    ports:
      - '3000:3000'
    command: ['bun', 'run', 'dev']
  scrapper-api:
    build: ./backend
    container_name: backend-api
    ports:
      - '3030:3030'
    # command: ['python', 'app']