services:

  nextjs-docker:
    build: ./frontend
    ports:
      - '5000:5000'
    restart: unless-stopped
    command: [ 'bun', 'run', 'dev' ]

  node-api:
    build: ./backend/node
    ports:
      - '3050:3050'
    restart: unless-stopped
    networks:
      - backend

  python-api:
    build: ./backend/python
    ports:
      - '3030:3030'
    restart: unless-stopped
    networks:
      - backend

  python-ai-api:
    build: ./backend/ai
    ports:
      - '3033:3033'
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
